SELECT TOP (1000) [anio]
      ,[descripcion_ciiu]
      ,[sector]
      ,[departamento]
      ,[provincia]
      ,[distrito]
      ,[tamano_empresa]
      ,[prom_venta_miles_soles]
      ,[trabajadores]
      ,[descripcion_partida]
      ,[fob_miles_dolares]
      ,[mes]
      ,[especie]
      ,[tipo_consumo]
  FROM [PescaExportadora].[dbo].[PESCA_LIMPIA]
